# CV2读取图像

In [5]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
img = cv2.imread('test1.jpg')  # HWC
print('img_shape',img.shape)     #读取数据的形状
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
print("img_shape",img.shape)
print('img_size',img.size)       #读取数据的大小
print('img_dtype',img.dtype)     #读取数据的编码格式
print('img',img)                 #打印img数据
print('img_type',type(img))      #读取img的数据类型

# b, g, r = cv2.split(img)    #通道分离,每个都是(H,W)
# zeros = np.zeros(img.shape[:2],dtype='uint8') # (H,W)
# merge_r = cv2.merge([r,zeros,zeros]) # HWC
# merge_g = cv2.merge([zeros,g,zeros])
# merge_b = cv2.merge([zeros,zeros,b])
# print(merge_r)
# plt.subplot(231);plt.imshow(b)
# plt.subplot(232);plt.imshow(g)
# plt.subplot(233);plt.imshow(r)
# plt.subplot(234);plt.imshow(merge_r)
# plt.subplot(235);plt.imshow(merge_g)
# plt.subplot(236);plt.imshow(merge_b)
# plt.show()

# cv2.imshow('img',img)   #显示图片
# cv2.waitKey(0)
# cv2.destroyAllWindows()

img_shape (512, 512, 3)
img_shape (512, 512, 3)
img_size 786432
img_dtype uint8
img [[[ 97 160 213]
  [ 97 160 213]
  [ 97 160 213]
  ...
  [ 94 163 222]
  [ 94 163 222]
  [ 94 163 222]]

 [[ 97 160 213]
  [ 97 160 213]
  [ 97 160 213]
  ...
  [ 94 163 222]
  [ 94 163 222]
  [ 94 163 222]]

 [[ 97 160 213]
  [ 97 160 213]
  [ 97 160 213]
  ...
  [ 94 163 222]
  [ 94 163 222]
  [ 94 163 222]]

 ...

 [[124 109  76]
  [119 104  71]
  [116 101  68]
  ...
  [132 146  59]
  [126 138  52]
  [144 157  69]]

 [[103  87  54]
  [102  86  53]
  [108  92  59]
  ...
  [136 149  61]
  [124 137  49]
  [134 147  57]]

 [[ 73  57  24]
  [ 90  74  41]
  [ 98  82  49]
  ...
  [147 160  72]
  [128 141  51]
  [126 139  49]]]
img_type <class 'numpy.ndarray'>


# matplotlib读取图像

In [7]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
img = plt.imread('test1.jpg')  #HWC
print('img_shape',img.shape)     #读取数据的形状
print('img_size',img.size)       #读取数据的大小
print('img_dtype',img.dtype)     #读取数据的编码格式
print('img',img)                 #打印img数据
print('img_type',type(img))      #读取img的数据类型

# r, g, b = cv2.split(img)    #通道分离
# # print(img.shape[:2])
# zeros = np.zeros(img.shape[:2],dtype='uint8')
# merge_r = cv2.merge([r,zeros,zeros])
# merge_g = cv2.merge([zeros,g,zeros])
# merge_b = cv2.merge([zeros,zeros,b])

# plt.subplot(231);plt.imshow(r)
# plt.subplot(232);plt.imshow(g)
# plt.subplot(233);plt.imshow(b)
# plt.subplot(234);plt.imshow(merge_r)
# plt.subplot(235);plt.imshow(merge_g)
# plt.subplot(236);plt.imshow(merge_b)
# plt.show()

# plt.imshow(img)
# plt.show()

# # cv2.imshow('img',img)   #显示图片
# cv2.waitKey(0)
# cv2.destroyAllWindows()

img_shape (512, 512, 3)
img_size 786432
img_dtype uint8
img [[[ 97 160 213]
  [ 97 160 213]
  [ 97 160 213]
  ...
  [ 94 163 222]
  [ 94 163 222]
  [ 94 163 222]]

 [[ 97 160 213]
  [ 97 160 213]
  [ 97 160 213]
  ...
  [ 94 163 222]
  [ 94 163 222]
  [ 94 163 222]]

 [[ 97 160 213]
  [ 97 160 213]
  [ 97 160 213]
  ...
  [ 94 163 222]
  [ 94 163 222]
  [ 94 163 222]]

 ...

 [[124 109  76]
  [119 104  71]
  [116 101  68]
  ...
  [133 145  59]
  [126 138  52]
  [144 156  70]]

 [[103  87  54]
  [102  86  53]
  [108  92  59]
  ...
  [136 149  61]
  [124 137  49]
  [134 147  59]]

 [[ 73  56  26]
  [ 90  73  43]
  [ 98  82  49]
  ...
  [147 160  72]
  [128 141  51]
  [126 139  49]]]
img_type <class 'numpy.ndarray'>
