In [2]:
import torch
from torch import nn

# def corr2d_multi_in(X, K):
#     # 沿着X和K的第0维（通道维）分别计算再相加
#     res = d2l.corr2d(X[0, :, :], K[0, :, :])
#     for i in range(1, X.shape[0]):
#         res += d2l.corr2d(X[i, :, :], K[i, :, :])
#     return res

def corr2d(X, K):  
    h, w = K.shape
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i: i + h, j: j + w] * K).sum()
    return Y

In [3]:
X = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
K = torch.tensor([[0, 1], [2, 3]])
corr2d(X, K)

tensor([[19., 25.],
        [37., 43.]])

In [26]:
import torch
X = torch.tensor([
                    [[1,2,3],[4,5,6],[7,8,9]],
                    [[1,1,1],[1,1,1],[1,1,1]],
                    [[2,2,2],[2,2,2],[2,2,2]]
                  ])
 
K = torch.tensor([
                [
                  [[1]],[[2]],[[3]]
                ],
                [
                  [[4]],[[1]],[[1]]
                ],
                [
                  [[3]],[[2]],[[3]]
                ]
                ])
print(K.shape)

torch.Size([3, 3, 1, 1])


In [27]:
import d2lzh_pytorch as d2l
def corr2d_multi_in(X, K):
    # 沿着X和K的第0维（通道维）分别计算再相加
    res = d2l.corr2d(X[0, :, :], K[0, :, :])
    for i in range(1, X.shape[0]):
        res += d2l.corr2d(X[i, :, :], K[i, :, :])
    return res
def corr2d_multi_in_out(X,K):
    return torch.stack([corr2d_multi_in(X,k) for k in K])
 
corr2d_multi_in_out(X,K)

tensor([[[ 9., 10., 11.],
         [12., 13., 14.],
         [15., 16., 17.]],

        [[ 7., 11., 15.],
         [19., 23., 27.],
         [31., 35., 39.]],

        [[11., 14., 17.],
         [20., 23., 26.],
         [29., 32., 35.]]])

In [4]:
import torch
from torch import nn

net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))
X = torch.rand(size=(2, 4))
# 我们需要给共享层一个名称，以便可以引用它的参数。
shared = nn.Linear(8, 8)
net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(),
                    shared, nn.ReLU(),
                    shared, nn.ReLU(),
                    nn.Linear(8, 1))
net(X)
# 检查参数是否相同
print(net[2].weight.data[0] == net[4].weight.data[0])
print(net[2])
net[2].weight.data[0, 0] = 100
# 确保它们实际上是同一个对象，而不只是有相同的值。
print(net[2].weight.data[0] == net[4].weight.data[0])

tensor([True, True, True, True, True, True, True, True])
Linear(in_features=8, out_features=8, bias=True)
tensor([True, True, True, True, True, True, True, True])
