In [9]:
import torch #导入torch
x = torch.arange(16)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
x.shape
# x.size() 这俩都可以


torch.Size([12])

In [10]:
x.numel()

16

In [5]:
X = x.reshape(3, 4) #改变张量的形状
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

将张量合并

In [11]:
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,2],[1,2,3,4],[4,3,2,1]])
torch.cat((x,y),dim=0) , torch.cat((x,y),dim=1) #dim=0 按行合并,dim=1 按列合并

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  2.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  2.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

通过逻辑运算符构建二元张量

In [12]:
x == y

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

张量求和

In [13]:
x.sum()

tensor(66.)

即使形状不同，可调用广播机制来执行元素操作

遵循规则：
1. 每个张量至少一个维度
2. 广播时，从尾部维度起，满足尺寸大小相等或其中一个为1或其中一个不存在

In [38]:
a = torch.arange(16).reshape((1,4,1,4))
b = torch.arange(8).reshape((2,4))
a,b

(tensor([[[[ 0,  1,  2,  3]],
 
          [[ 4,  5,  6,  7]],
 
          [[ 8,  9, 10, 11]],
 
          [[12, 13, 14, 15]]]]),
 tensor([[0, 1, 2, 3],
         [4, 5, 6, 7]]))

In [39]:
a+b

tensor([[[[ 0,  2,  4,  6],
          [ 4,  6,  8, 10]],

         [[ 4,  6,  8, 10],
          [ 8, 10, 12, 14]],

         [[ 8, 10, 12, 14],
          [12, 14, 16, 18]],

         [[12, 14, 16, 18],
          [16, 18, 20, 22]]]])

运行一些操作可能会导致为新结果分配内存

In [41]:
before = id(b)
b = a+b
id(b) == before

False

执行原地操作

In [43]:
c = torch.zeros_like(b) #与b元素类型相同，但内容为0
print('id(c):',id(c))
c[:] = a+b
print("id(c):",id(c))

id(c): 2458854997632
id(c): 2458854997632


若后续计算中未重复使用c，也可使用`c[:]=a+b`或`c+=b`来减少操作的内存内存开销

In [45]:
before = id(b)
b += a
id(b) == before

True