在计算y关于x的梯度之前，需要存储梯度

In [1]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [8]:
x.requires_grad_(True) # 等价于x = torch.arange(4.0,requires_grad=True)
x.grad #默认为none

In [3]:
#计算y
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [11]:
#默认情况下，pytorch会累积梯度，需要清除之前的值
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [14]:
#对非标量调用`backward`需要传入一个`gradient`参数，该参数指定微分
x.grad.zero_()
y = x*x
#等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

将某些计算移动到记录的计算图之外

In [15]:
x.grad.zero_()
y = x*x
u = y.detach()
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [16]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 *x

tensor([True, True, True, True])

即便构建函数的计算图需要通过Python控制流，仍可计算得到变量的梯度

In [18]:
def f(a):
    b = a *2
    while b.norm() < 1000:
        b =b *2
    if b.sum() >0:
        c = b
    else:
        c = 100 *b
    return c
a = torch.randn(size=(),requires_grad=True)
d = f(a)
d.backward()

C:\Users\ldh46\AppData\Local\Temp/ipykernel_30000/1492267940.py:13: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  d.grad
