# 随机种子
1. `torch.manual_seed(seed:int)`用于生成随机种子，以保证初始化的参数可复现。

In [7]:
import torch
torch.manual_seed(2)
print(torch.rand(1,2))

tensor([[0.6147, 0.3810]])


`torch.cuda.manual_seed(int.seed)`为当前GPU设置随机种子
`torch.cuda.manual_seed_all(int.seed)`为所有的GPU设置种子

`tensor。uniform`

`tensor.uniform_()` 令tensor从均匀分布中抽样数值进行填充

In [12]:
import torch
A = torch.randn(2,2)
print(A)
B = A.uniform_(-3,3)
print(B)

tensor([[ 0.5731,  0.5409],
        [-0.3919, -1.0427]])
tensor([[-2.9384, -0.2038],
        [-0.2377,  2.1279]])
